"""WU-10 Phase 2: false-positive validation harness for a burn-scar COG.

The WU-1 audit (`scripts/09_burn_scar_audit.py`) measured rank agreement but
NOT the false-positive rate on unburned land, and chose no threshold with a
precision/recall trade-off in view. This script closes that gap:

  1. Rasterise the matched-window ICNF Areas Ardidas perimeters onto the COG
     grid (explicit CRS assertion on both the vector and the raster).
  2. Draw a fuel-class-stratified true-negative sample from the unburned
     pixels (seed 42), proportional to fuel-class prevalence.
  3. Sweep thresholds 0.1..0.9 (step 0.05) computing precision / recall / F1 /
     IoU / FPR over the union of ICNF-positive pixels and the TN sample; write
     the full sweep to a PR-curve JSON under outputs/diagnostics/.
  4. Cross-tab predicted-positive vs fuel class (which fuel types drive FPs).
  5. Report the headline metrics at the chosen threshold (default 0.5).
  6. Assert no temporal leakage: every S2 item in the COG provenance must have
     been observed on or before the ICNF perimeter end date of the window.
  7. Append the result to `docs/burn_scar_audit.md` (never overwrite) with the
     repo's `<!-- generated by: ... -->` citation convention.

Determinism: seed 42 everywhere (CLAUDE.md non-negotiable #4).

Terminology guard (non-negotiable #6): the COG value is a burn-scar inference
score (relative model score / "above threshold" / "matched area"), NEVER a
calibrated probability, a risk, or a forecast. Burn SCARS detected = post-event
spectral signatures of fires that already happened. Not ignition prediction.

Usage:

    uv run python scripts/16_burn_scar_validate.py \\
        --cog outputs/cogs/burn_scar_<run_id>.tif \\
        --fuel-cog outputs/cogs/fuel_class_<run_id>.tif \\
        --threshold 0.5 \\
        --append-doc docs/burn_scar_audit.md

A smoke gate (`--smoke`) runs the identical code path on a tiny synthetic grid
with no network, so the harness itself is provable before the pilot run.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np

if TYPE_CHECKING:
    from collections.abc import Sequence

# Reuse the live ICNF fetch + layer mapping from the WU-1 audit script so the
# perimeter source can never drift between the two crosschecks. The module name
# starts with a digit, so import it via importlib from the scripts dir.
import importlib.util

_AUDIT_PATH = Path(__file__).resolve().parent / "09_burn_scar_audit.py"
_spec = importlib.util.spec_from_file_location("burn_scar_audit_09", _AUDIT_PATH)
assert _spec is not None and _spec.loader is not None
_audit = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_audit)

from wildfire_exposure_eo.stac import code_commit_sha

SEED = 42
TN_SAMPLE_SIZE = 10_000
THRESHOLD_SWEEP = [round(0.1 + 0.05 * i, 2) for i in range(17)]  # 0.10 .. 0.90
DEFAULT_DIAG_DIR = Path("outputs/diagnostics")
COG_CRS = "EPSG:4326"


def _load_cog(cog_path: Path) -> dict[str, Any]:
    """Read a burn-scar COG + its embedded provenance; assert CRS is EPSG:4326."""
    import rasterio

    with rasterio.open(cog_path) as src:
        prob = src.read(1).astype(np.float32)
        nodata = src.nodata
        transform = src.transform
        crs = src.crs
        bounds = src.bounds
        tags = src.tags()
    assert crs is not None and crs.to_epsg() == 4326, f"burn-scar COG must be EPSG:4326, got {crs}"
    provenance = json.loads(tags["WILDFIRE_EXPOSURE_EO_PROVENANCE"])
    valid = (prob != nodata) if nodata is not None else np.isfinite(prob)
    return {
        "prob": prob,
        "nodata": nodata,
        "transform": transform,
        "shape": prob.shape,
        "bounds": bounds,
        "valid": valid,
        "provenance": provenance,
    }


def _rasterise_icnf(
    bounds: Any,
    shape: tuple[int, int],
    transform: Any,
    *,
    layer_id: int,
    window_start: datetime,
    overlap_end: datetime,
) -> tuple[np.ndarray, int]:
    """Boolean ICNF burned mask on the COG grid; CRS asserted before rasterising.

    Returns `(mask, n_polys_in_window)`. Polygons are filtered to those whose
    DH_Inicio falls inside `[window_start, overlap_end]` (no temporal leakage).
    """
    from rasterio.features import rasterize
    from shapely.geometry import shape as shp_shape

    bbox = (bounds.left, bounds.bottom, bounds.right, bounds.top)
    features = _audit.fetch_icnf_features(bbox, layer_id=layer_id)
    in_window = []
    for feat in features:
        raw = feat.get("properties", {}).get("DH_Inicio")
        if raw is None:
            continue
        started = datetime.fromtimestamp(raw / 1000.0, tz=UTC)
        if window_start <= started <= overlap_end:
            in_window.append(feat)
    print(
        f"[validate] ICNF layer {layer_id}: {len(features)} intersect bbox, "
        f"{len(in_window)} start within {window_start.date()}..{overlap_end.date()}",
        file=sys.stderr,
    )
    # The ICNF MapServer is queried with outSR=4326 (see 09_burn_scar_audit.py),
    # and the COG is asserted EPSG:4326 above — both sides are explicitly WGS84
    # before any rasterisation (CLAUDE.md non-negotiable #2).
    if in_window:
        mask = rasterize(
            [(shp_shape(f["geometry"]), 1) for f in in_window],
            out_shape=shape,
            transform=transform,
            fill=0,
            dtype="uint8",
        )
        assert mask is not None
        return mask.astype(bool), len(in_window)
    return np.zeros(shape, dtype=bool), 0


def _fuel_on_cog_grid(
    fuel_cog_path: Path,
    shape: tuple[int, int],
    transform: Any,
) -> np.ndarray:
    """Reproject the fuel-class COG onto the burn-scar COG grid (nearest).

    Fuel classes are categorical, so nearest resampling only. The fuel COG is
    in EPSG:32629; it is explicitly reprojected to the COG's EPSG:4326 grid
    (non-negotiable #2 — implicit reprojection is forbidden).
    """
    import rasterio
    from rasterio.enums import Resampling
    from rasterio.warp import reproject

    with rasterio.open(fuel_cog_path) as src:
        assert src.crs is not None, "fuel COG carries no CRS"
        src_crs = src.crs
        src_data = src.read(1)
        src_transform = src.transform
        src_nodata = src.nodata if src.nodata is not None else 255

    dst = np.full(shape, src_nodata, dtype=src_data.dtype)
    reproject(
        source=src_data,
        destination=dst,
        src_transform=src_transform,
        src_crs=src_crs,
        dst_transform=transform,
        dst_crs=COG_CRS,
        resampling=Resampling.nearest,
        src_nodata=src_nodata,
        dst_nodata=src_nodata,
    )
    return dst


def _stratified_tn_sample(
    unburned_valid: np.ndarray,
    fuel: np.ndarray,
    fuel_nodata: int,
    *,
    n: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, dict[int, int]]:
    """Flat indices of a fuel-class-stratified TN sample, plus stratum sizes.

    Draws from the unburned + valid pixel set, allocating each fuel class a
    share of `n` proportional to its prevalence in that set. Logs the strata.
    """
    flat_unburned = np.flatnonzero(unburned_valid.ravel())
    flat_fuel = fuel.ravel()[flat_unburned]
    have_fuel = flat_fuel != fuel_nodata
    flat_unburned = flat_unburned[have_fuel]
    flat_fuel = flat_fuel[have_fuel]
    if flat_unburned.size == 0:
        raise ValueError("no unburned valid pixels with a fuel class to sample")

    classes, counts = np.unique(flat_fuel, return_counts=True)
    total = int(counts.sum())
    target = n if n <= total else total
    strata: dict[int, int] = {}
    chosen: list[np.ndarray] = []
    for cls, cnt in zip(classes.tolist(), counts.tolist(), strict=True):
        quota = min(round(target * cnt / total), cnt)
        if quota <= 0:
            strata[int(cls)] = 0
            continue
        pool = flat_unburned[flat_fuel == cls]
        picked = rng.choice(pool, size=quota, replace=False)
        chosen.append(picked)
        strata[int(cls)] = int(quota)
    sample = np.concatenate(chosen) if chosen else np.empty(0, dtype=np.int64)
    print(f"[validate] stratified TN sample: {sample.size} pixels across strata:", file=sys.stderr)
    for cls in sorted(strata):
        print(f"[validate]   fuel class {cls}: {strata[cls]}", file=sys.stderr)
    return sample, strata


def _metrics_at(prob_eval: np.ndarray, y_true: np.ndarray, threshold: float) -> dict[str, float]:
    """precision / recall / F1 / IoU / FPR for one threshold on the eval set."""
    pred = prob_eval >= threshold
    tp = int(np.sum(pred & y_true))
    fp = int(np.sum(pred & ~y_true))
    fn = int(np.sum(~pred & y_true))
    tn = int(np.sum(~pred & ~y_true))
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    iou = tp / (tp + fp + fn) if (tp + fp + fn) else 0.0
    fpr = fp / (fp + tn) if (fp + tn) else 0.0
    return {
        "threshold": round(threshold, 4),
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "precision": round(precision, 6),
        "recall": round(recall, 6),
        "f1": round(f1, 6),
        "iou": round(iou, 6),
        "fpr": round(fpr, 6),
    }


def _crosstab_predicted_vs_fuel(
    prob: np.ndarray,
    fuel: np.ndarray,
    valid: np.ndarray,
    fuel_nodata: int,
    threshold: float,
) -> list[dict[str, Any]]:
    """Predicted-positive rate by fuel class over the full valid AOI."""
    rows: list[dict[str, Any]] = []
    pred = (prob >= threshold) & valid
    fuel_v = np.where(valid, fuel, fuel_nodata)
    classes = sorted(int(c) for c in np.unique(fuel_v) if c != fuel_nodata)
    for cls in classes:
        cls_mask = (fuel_v == cls) & valid
        n_cls = int(np.sum(cls_mask))
        n_pred = int(np.sum(pred & cls_mask))
        rate = n_pred / n_cls if n_cls else 0.0
        rows.append(
            {
                "fuel_class": cls,
                "valid_pixels": n_cls,
                "predicted_positive": n_pred,
                "predicted_positive_rate": round(rate, 6),
            }
        )
    return rows


def _assert_no_temporal_leakage(provenance: dict[str, Any], overlap_end: datetime) -> None:
    """Every S2 item id encodes its sensing date; assert it is <= overlap_end.

    S2 L2A item ids embed the sensing timestamp as the 3rd underscore field,
    e.g. S2A_MSIL2A_20250607T113911_R080_T29TNF. We parse that date and assert
    it does not fall after the ICNF window end (WU-7 leakage rule).
    """
    bad: list[str] = []
    for item_id in provenance.get("s2_item_ids", []):
        parts = item_id.split("_")
        stamp = next((p for p in parts if len(p) >= 8 and p[:8].isdigit()), None)
        if stamp is None:
            print(f"[validate] WARN: cannot parse a date from item id {item_id}", file=sys.stderr)
            continue
        sensed = datetime.strptime(stamp[:8], "%Y%m%d").replace(tzinfo=UTC)
        if sensed > overlap_end:
            bad.append(f"{item_id} (sensed {sensed.date()})")
    if bad:
        raise AssertionError(
            "temporal leakage: S2 items observed after the ICNF window end "
            f"{overlap_end.date()}: {bad}"
        )
    print(
        f"[validate] temporal-leakage check OK: all "
        f"{len(provenance.get('s2_item_ids', []))} S2 item(s) sensed <= {overlap_end.date()}",
        file=sys.stderr,
    )


def _build_synthetic_smoke() -> dict[str, Any]:
    """Tiny in-memory synthetic dataset exercising the full metric/IO path."""
    rng = np.random.default_rng(SEED)
    shape = (64, 64)
    prob = rng.random(shape, dtype=np.float64).astype(np.float32)
    burned = np.zeros(shape, dtype=bool)
    burned[10:20, 10:20] = True
    prob[burned] = 0.9  # make the burned block score high so recall is non-trivial
    valid = np.ones(shape, dtype=bool)
    fuel = rng.integers(1, 5, size=shape).astype(np.uint8)
    fuel_nodata = 255
    return {
        "prob": prob,
        "valid": valid,
        "burned": burned,
        "fuel": fuel,
        "fuel_nodata": fuel_nodata,
        "n_polys": 1,
        "window_start": datetime(2025, 6, 9, tzinfo=UTC),
        "overlap_end": datetime(2025, 12, 31, tzinfo=UTC),
        "provenance": {
            "run_id": "smoke",
            "code_commit_sha": "smoke",
            "model_id": "smoke",
            "hf_revision_sha": "smoke",
            "reducer": "p85",
            "s2_item_ids": ["S2A_MSIL2A_20250607T113911_R080_T29TNF"],
        },
        "cog_path": Path("(synthetic smoke grid)"),
    }


def _evaluate(
    prob: np.ndarray,
    valid: np.ndarray,
    burned: np.ndarray,
    fuel: np.ndarray,
    fuel_nodata: int,
    threshold: float,
    rng: np.random.Generator,
) -> dict[str, Any]:
    """Stratified TN sample + threshold sweep + cross-tab + headline metrics."""
    burned_valid = burned & valid
    unburned_valid = (~burned) & valid
    tn_idx, strata = _stratified_tn_sample(
        unburned_valid, fuel, fuel_nodata, n=TN_SAMPLE_SIZE, rng=rng
    )

    pos_idx = np.flatnonzero(burned_valid.ravel())
    eval_idx = np.concatenate([pos_idx, tn_idx])
    flat_prob = prob.ravel()[eval_idx]
    y_true = np.concatenate([np.ones(pos_idx.size, dtype=bool), np.zeros(tn_idx.size, dtype=bool)])

    sweep = [_metrics_at(flat_prob, y_true, t) for t in THRESHOLD_SWEEP]
    headline = _metrics_at(flat_prob, y_true, threshold)
    crosstab = _crosstab_predicted_vs_fuel(prob, fuel, valid, fuel_nodata, threshold)

    valid_prob = prob[valid]
    frac_ge_05 = float(np.mean(valid_prob >= 0.5)) if valid_prob.size else 0.0
    median_prob = float(np.median(valid_prob)) if valid_prob.size else 0.0
    return {
        "n_positive_pixels": int(pos_idx.size),
        "n_tn_sample": int(tn_idx.size),
        "tn_strata": strata,
        "valid_pixels": int(valid_prob.size),
        "median_prob": round(median_prob, 6),
        "frac_above_05": round(frac_ge_05, 6),
        "sweep": sweep,
        "headline": headline,
        "crosstab": crosstab,
    }


def _doc_section(
    cog_path: Path,
    provenance: dict[str, Any],
    result: dict[str, Any],
    threshold: float,
    commit: str,
    n_polys: int,
) -> str:
    """Markdown block appended to docs/burn_scar_audit.md (terminology-guarded)."""
    h = result["headline"]
    reducer = provenance.get("reducer", "max")
    lines = [
        "",
        "## WU-10 validation — remediation results",
        "",
        f"<!-- generated by: scripts/16_burn_scar_validate.py at {commit} -->",
        "",
        f"COG: `{cog_path}` (run `{provenance.get('run_id')}`, reducer `{reducer}`, "
        f"model `{provenance.get('model_id')}` @ `{str(provenance.get('hf_revision_sha'))[:8]}`).",
        f"ICNF perimeters in matched window: {n_polys}. True-negative sample: "
        f"{result['n_tn_sample']} pixels, fuel-class-stratified (seed {SEED}).",
        "",
        "Burn SCARS detected — post-event spectral signatures of fires that already "
        "happened. The values below describe how many pixels score *above threshold* "
        "and how that set overlaps ICNF-mapped *matched area*. Nothing here is a "
        "calibrated probability, a risk, or a forecast.",
        "",
        "| metric | baseline (WU-1 COG) | remediated COG |",
        "|---|---|---|",
        f"| frac_above_05 | 0.473 | {result['frac_above_05']:.3f} |",
        f"| median score | 0.470 | {result['median_prob']:.3f} |",
        f"| FPR@{threshold:g} | n/a (not measured in WU-1) | {h['fpr']:.4f} |",
        f"| precision@{threshold:g} | n/a | {h['precision']:.4f} |",
        f"| recall@{threshold:g} | n/a | {h['recall']:.4f} |",
        f"| F1@{threshold:g} | n/a | {h['f1']:.4f} |",
        f"| IoU@{threshold:g} | n/a | {h['iou']:.4f} |",
        "",
        "Predicted-positive rate by fuel class (drivers of false positives):",
        "",
        "| fuel class | valid pixels | predicted positive | rate |",
        "|---|---|---|---|",
    ]
    for row in result["crosstab"]:
        lines.append(
            f"| {row['fuel_class']} | {row['valid_pixels']} | "
            f"{row['predicted_positive']} | {row['predicted_positive_rate']:.4f} |"
        )
    lines.append("")
    return "\n".join(lines)


def _print_sweep(sweep: Sequence[dict[str, Any]]) -> None:
    print("[validate] threshold sweep (precision / recall / F1 / IoU / FPR):", file=sys.stderr)
    print("| thr | precision | recall | F1 | IoU | FPR |", file=sys.stderr)
    print("|---|---|---|---|---|---|", file=sys.stderr)
    for s in sweep:
        print(
            f"| {s['threshold']:.2f} | {s['precision']:.4f} | {s['recall']:.4f} | "
            f"{s['f1']:.4f} | {s['iou']:.4f} | {s['fpr']:.4f} |",
            file=sys.stderr,
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cog", type=Path, default=None, help="burn-scar inference COG")
    parser.add_argument("--fuel-cog", type=Path, default=None, help="fuel-class COG for strata")
    parser.add_argument("--layer-id", type=int, default=_audit.ICNF_2025_LAYER_ID)
    parser.add_argument("--vintage-end", default="2025-12-31")
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument("--diag-dir", type=Path, default=DEFAULT_DIAG_DIR)
    parser.add_argument("--pr-curve-out", type=Path, default=None)
    parser.add_argument("--append-doc", type=Path, default=None)
    parser.add_argument("--smoke", action="store_true", help="synthetic in-memory grid, no network")
    args = parser.parse_args()

    rng = np.random.default_rng(SEED)

    if args.smoke:
        data = _build_synthetic_smoke()
        cog_path = data["cog_path"]
        provenance = data["provenance"]
        window_start, overlap_end = data["window_start"], data["overlap_end"]
        prob, valid, burned = data["prob"], data["valid"], data["burned"]
        fuel, fuel_nodata = data["fuel"], data["fuel_nodata"]
        n_polys = data["n_polys"]
    else:
        if args.cog is None or args.fuel_cog is None:
            parser.error("--cog and --fuel-cog are required unless --smoke is set")
        cog_path = args.cog
        cog = _load_cog(cog_path)
        provenance = cog["provenance"]
        prob, valid = cog["prob"], cog["valid"]
        window_start = datetime.fromisoformat(provenance["window_start"]).replace(tzinfo=UTC)
        window_end = datetime.fromisoformat(provenance["window_end"]).replace(tzinfo=UTC)
        vintage_end = datetime.fromisoformat(args.vintage_end).replace(tzinfo=UTC)
        overlap_end = min(window_end, vintage_end)
        if overlap_end <= window_start:
            print("no overlap between the COG window and the ICNF vintage", file=sys.stderr)
            return 2
        burned, n_polys = _rasterise_icnf(
            cog["bounds"],
            cog["shape"],
            cog["transform"],
            layer_id=args.layer_id,
            window_start=window_start,
            overlap_end=overlap_end,
        )
        fuel = _fuel_on_cog_grid(args.fuel_cog, cog["shape"], cog["transform"])
        fuel_nodata = 255

    _assert_no_temporal_leakage(provenance, overlap_end)

    result = _evaluate(prob, valid, burned, fuel, fuel_nodata, args.threshold, rng)
    _print_sweep(result["sweep"])

    h = result["headline"]
    print("", file=sys.stderr)
    print("=" * 72, file=sys.stderr)
    print("WU-10 BURN-SCAR VALIDATION", file=sys.stderr)
    print("=" * 72, file=sys.stderr)
    print(f"COG: {cog_path}  reducer={provenance.get('reducer', 'max')}", file=sys.stderr)
    print(f"valid pixels: {result['valid_pixels']:,}", file=sys.stderr)
    print(f"median score: {result['median_prob']:.4f}", file=sys.stderr)
    print(f"frac >= 0.5:  {result['frac_above_05'] * 100:.2f}%", file=sys.stderr)
    print(f"ICNF positive pixels: {result['n_positive_pixels']:,}", file=sys.stderr)
    print(
        f"@thr={args.threshold:g}: precision={h['precision']:.4f} recall={h['recall']:.4f} "
        f"F1={h['f1']:.4f} IoU={h['iou']:.4f} FPR={h['fpr']:.4f}",
        file=sys.stderr,
    )
    print("=" * 72, file=sys.stderr)

    commit = code_commit_sha(cwd=Path.cwd())
    run_at = datetime.now(UTC)
    run_id = run_at.strftime("%Y%m%dT%H%M%SZ")
    args.diag_dir.mkdir(parents=True, exist_ok=True)
    pr_out = args.pr_curve_out or (
        args.diag_dir / (f"16_pr_curve_smoke_{run_id}.json" if args.smoke else "16_pr_curve.json")
    )
    payload = {
        "run_id": run_id,
        "generated_by": "scripts/16_burn_scar_validate.py",
        "code_commit_sha": commit,
        "created_at_utc": run_at.isoformat(),
        "seed": SEED,
        "smoke": bool(args.smoke),
        "cog_path": str(cog_path),
        "cog_provenance_run_id": provenance.get("run_id"),
        "reducer": provenance.get("reducer", "max"),
        "threshold_headline": args.threshold,
        "icnf_polys_in_window": n_polys,
        "value_semantics": (
            "burn-scar inference score (Prithvi-Burn-Scar class-1 softmax); relative "
            "model score thresholded into above/below; NOT a calibrated probability "
            "and NOT a fire forecast"
        ),
        **result,
    }
    pr_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(f"[validate] PR-curve JSON: {pr_out}", file=sys.stderr)

    if args.append_doc is not None:
        section = _doc_section(cog_path, provenance, result, args.threshold, commit, n_polys)
        with args.append_doc.open("a") as fh:
            fh.write(section)
        print(f"[validate] appended section to {args.append_doc}", file=sys.stderr)

    print(
        json.dumps(
            {"pr_curve": str(pr_out), "headline": h, "frac_above_05": result["frac_above_05"]}
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
